services:
  app:
    image: ghcr.io/patersss/neoflexvacationcalculator:${GIT_COMMIT_HASH}
    restart: on-failure
    container_name: calculator
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
    