name: test ci/cd
on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
    build_push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Log in to registry
          uses: docker/login-action@v3
          with:
            registry: https://ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              ghcr.io/patersss/neoflexvacationcalculator:latest
              ghcr.io/patersss/neoflexvacationcalculator:${{ github.sha }}

    deploy:
      runs-on: ubuntu-latest
      needs:
        - build_push
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: create env file
          run: |
            echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
        - name: Docker Stack Deploy
          uses: cssnr/stack-deploy-action@v1
          with:
            name: game
            file: compose.yaml
            host: 176.98.178.227
            user: paradox
            ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
            env_file: ./envfile
